In [17]:
import pandas as pd
import numpy as np
from rapidfuzz.fuzz import ratio
import re
import src_any_abogados_fuzzymerge_df_er_v1_sec as src
import src_any_abogados_numbersmerge_df_er_v1_sec as src2
#import src_any_abogados_emailmerge_df_er_v1_sec as src3
import src_any_abogados_test_df_er_v1_sec as src4

In [18]:
pd.set_option("display.max_rows", None)

In [19]:
def remove_empty_columns(df):

    df_aux = df.copy()
    empty_columns = list(df_aux.columns[df_aux.isna().mean() == 1])   # Almacena en una lista las columnas que están totalmente vacias
    if "Unnamed: 0" in df_aux.columns:
        empty_columns.append("Unnamed: 0")
    df_aux = df_aux.drop(columns=empty_columns)
    return df_aux

In [20]:
#Lectura de tablas
df_gm_o = pd.read_csv("datasets/Dataset_GM_PR.csv")
df_ca_o = pd.read_csv("datasets/datos_abogados.csv") 
df_naics_o = pd.read_csv("datasets/NAICS_Puerto Rico.csv")

df_gm_o = remove_empty_columns(df_gm_o)
df_ca_o = remove_empty_columns(df_ca_o)
df_naics_o = remove_empty_columns(df_naics_o)

df_gm_o["Email"] = df_gm_o["Email"].str.strip().replace(["Not available"], np.nan)

# Agregar columna que indique de dónde viene el registro
df_gm_o["dataset"] = "gm"
df_ca_o["dataset"] = "ca"
df_naics_o["dataset"] = "naics"

In [21]:
#Agregar columna "is Firm" para diferenciar Firma de Abogados
df_gm_o['is Firm'] = df_gm_o['Name'].apply(lambda x: bool(re.search(src.pattern_firma, str(x), flags=re.IGNORECASE)))

In [22]:
#DataFrame que almacena los registros que son firmas
df_gm_firmas = df_gm_o[df_gm_o["is Firm"]]

#DataFrame filtrado y almacena los registro que son abogados
df_gm_o = df_gm_o[~df_gm_o["is Firm"]]

#Normalización de nombres
df_gm_o["Clean_Name"] = df_gm_o["Name"].apply(lambda x: src.name_normalized(x)).str.lower()
df_ca_o["FULL NAME"] = df_ca_o["FULL NAME"].apply(lambda x: src.name_normalized(x)).str.lower()
df_naics_o["Name_N"] = df_naics_o["Name_N"].apply(lambda x: src.name_normalized(x)).str.lower()

#Reset index
df_gm_o = df_gm_o.reset_index(drop=True)
df_ca_o = df_ca_o.reset_index(drop=True)
df_naics_o = df_naics_o.reset_index(drop=True)

In [23]:
# Columnas importantes: Name, city, state_name, Address, Website,Phone,Google_category,Type,Email,Specialization,Education,ExperiencE
# Columnas a Analizar: zip, state_id, Orig Specialization
# NO Columnas importantes: Google_URL, population,Google_rank,Google_opinions,Google_category,Processed,Name AI

df_gm_o.isna().mean()

Name                   0.000000
Google_URL             0.000000
zip                    0.000000
city                   0.000000
state_id               0.000000
state_name             0.000000
population             0.000000
Address                0.067335
Website                0.659026
Phone                  0.085960
Google_rank            0.193410
Google_opinions        0.177650
Google_category        0.021490
Name len               0.000000
Type                   0.000000
Email                  0.793696
Orig Specialization    0.226361
Specialization         0.226361
Education              0.226361
Experience             0.226361
Processed              0.226361
Name AI                0.226361
dataset                0.000000
is Firm                0.000000
Clean_Name             0.000000
dtype: float64

In [24]:
# Columnas importantes: FULL NAME', 'FNAME', 'LNAME
# Columnas a Analizar: 
# NO Columnas importantes:

df_ca_o.isna().mean()

FULL NAME          0.000000
FNAME              0.000000
LNAME              0.000000
colegiacion        0.092222
rua                0.092593
correo             0.884444
tel_residencial    0.994074
tel_oficina        0.914074
tel_celular        0.957037
otro               0.994444
especialidades     0.635185
Practice Area      0.635185
delegacion         0.001481
State              0.001481
dataset            0.000000
dtype: float64

In [25]:
# Columnas importantes: FULL NAME', 'FNAME', 'LNAME
# Columnas a Analizar: 
# NO Columnas importantes:

df_naics_o.isna().mean()

Name_N                                      0.000000
ZoomInfo Contact ID                         0.000000
Last Name                                   0.000000
First Name                                  0.000000
Middle Name                                 0.517479
Job Title                                   0.127648
Job Title Hierarchy Level                   0.319915
Management Level                            0.686970
Job Start Date                              0.018008
Job Function                                0.462394
Department                                  0.396716
Direct Phone Number                         0.645657
Email Address                               0.253178
Email Domain                                0.253708
Mobile phone                                0.612818
Highest Level of Education                  0.658369
Contact Accuracy Score                      0.000000
Contact Accuracy Grade                      0.000000
ZoomInfo Contact Profile URL                0.000000
LinkedIn Contact Profile URL                0.317267
Person Street                               0.300847
Person City                                 0.217161
Person State                                0.081038
Person Zip Code                             0.275953
Country                                     0.070975
ZoomInfo Company ID                         0.000000
Company Name                                0.000000
Website                                     0.006356
Founded Year                                0.094280
Company HQ Phone                            0.090572
Fax                                         0.609110
Ticker                                      0.998941
Revenue (in 000s USD)                       0.000000
Revenue Range (in USD)                      0.000000
Employees                                   0.000000
Employee Range                              0.000000
SIC Code 1                                  0.000000
SIC Code 2                                  0.000000
SIC Codes                                   0.000000
NAICS Code 1                                0.000000
NAICS Code 2                                0.000000
NAICS Codes                                 0.000000
Primary Industry                            0.002119
Primary Sub-Industry                        0.974576
All Industries                              0.000000
All Sub-Industries                          0.969809
Industry Hierarchical Category              0.002119
Secondary Industry Hierarchical Category    0.974576
Alexa Rank                                  0.351695
ZoomInfo Company Profile URL                0.000000
LinkedIn Company Profile URL                0.155191
Facebook Company Profile URL                0.363347
Twitter Company Profile URL                 0.708686
Ownership Type                              0.000000
Business Model                              0.503708
Certified Active Company                    0.000000
Certification Date                          0.162606
Total Funding Amount (in 000s USD)          0.000000
Recent Funding Amount (in 000s USD)         0.000000
Recent Funding Round                        0.567797
Recent Funding Date                         0.567797
Recent Investors                            0.568326
All Investors                               0.568326
Company Street Address                      0.028072
Company City                                0.030191
Company State                               0.024894
Company Zip Code                            0.036547
Company Country                             0.002648
Full Address                                0.002648
Number of Locations                         0.080508
Query Name                                  0.000000
Subject 2 New                               0.999470
Body 2 New                                  0.999470
dataset                                     0.000000
dtype: float64

In [26]:
df_ca_o = src2.combine_columns_by_priority(df_ca_o,["tel_celular","tel_residencial","tel_oficina","otro"],"telefono")
df_naics_o = src2.combine_columns_by_priority(df_naics_o,["Mobile phone","Direct Phone Number"], "phone")

In [27]:
df_ca_o["telefono"] = df_ca_o["telefono"].apply(lambda phone: src2.normalized_phone(str(phone)) if pd.notnull(phone) else None)
df_naics_o["phone"] = df_naics_o["Mobile phone"].apply(lambda phone: src2.normalized_phone(str(phone)) if pd.notnull(phone) else None)

# Merge por coincidencia exacta de número de contacto

No se obtuvo ninguna coincidencia exacta por número de teléfono entre los 3 datasets.
Se obtuvo 3 coincidencias exactas entre los datasets del colegio de abogados y naics

In [28]:
#Merge entre gm y ca
df_gm_y_df_ca = src2.merge_by_contact_number(df_gm_o, df_ca_o, "Phone", "telefono", "Clean_Name", "FULL NAME")
print(df_gm_y_df_ca[["Clean_Name","FULL NAME","Phone","telefono","score"]].head())

                     Clean_Name                 FULL NAME Phone telefono  \
0  orville omar valentin rivera     maria barrera rosario   NaN     None
1  orville omar valentin rivera     martha berrios rivera   NaN     None
2  orville omar valentin rivera  catherine catala lasanta   NaN     None
3  orville omar valentin rivera      luis del valle colon   NaN     None
4  orville omar valentin rivera     juan encarnacion cruz   NaN     None

      score
0  0.367347
1  0.530612
2  0.384615
3  0.333333
4  0.326531

In [29]:
#Merge entre gm y naics
df_gm_y_df_naics = src2.merge_by_contact_number(df_gm_o, df_naics_o, "Phone", "phone", "Clean_Name", "Name_N")
print(df_gm_y_df_naics[["Clean_Name","Name_N","Phone","phone","score"]].head())

                     Clean_Name                          Name_N Phone phone  \
0  orville omar valentin rivera                    larry suckle   NaN  None
1  orville omar valentin rivera  alex giovanni rodriguez negron   NaN  None
2  orville omar valentin rivera                 aura colon sola   NaN  None
3  orville omar valentin rivera                     judy arroyo   NaN  None
4  orville omar valentin rivera      yolanda benitez de alegria   NaN  None

      score
0  0.300000
1  0.448276
2  0.325581
3  0.205128
4  0.407407

In [30]:
#Merge entre ca y naics  -->> **  # Salen 3 registros coincidencia exacta **
df_ca_y_df_naics = src2.merge_by_contact_number(df_ca_o, df_naics_o, "telefono", "phone", "FULL NAME", "Name_N")
print(df_ca_y_df_naics[["FULL NAME","Name_N","telefono","phone","score"]].head())

KeyboardInterrupt:

In [ ]:
#Merge COMPLETO
df_merged_full = src2.merge_by_contact_number(df_gm_y_df_ca, df_naics_o, "Phone", "phone", "FULL NAME", "Name_N")
print(df_merged_full[["Clean_Name","FULL NAME","Phone","telefono","score"]].head())

# Merge por coincidencia exacta de Email

In [ ]:
#Merge entre gm y ca    -->> ** 5 coincidencias exactas **
df_gm_y_df_ca = src3.merge_by_email(df_gm_o, df_ca_o, "Email", "correo", "Clean_Name", "FULL NAME")
print(df_gm_y_df_ca[["Clean_Name","FULL NAME","Email","correo","score"]].head())

#Merge entre gm y naics -->> NO COINCIDENCIAS
df_gm_y_df_naics = src3.merge_by_email(df_gm_o, df_naics_o, "Email", "Email Address", "Clean_Name", "Name_N")
print(df_gm_y_df_naics[["Clean_Name","Name_N","Phone","phone","score"]].head())

#Merge entre ca y naics  -->> ** 5 coincidencias exactas
df_ca_y_df_naics = src3.merge_by_email(df_ca_o, df_naics_o, "correo", "Email Address", "FULL NAME", "Name_N")
print(df_ca_y_df_naics[["FULL NAME","Name_N","correo","Email Address","score"]].head())               

#Merge COMPLETO   -->> NO COINCIDENCIAS
df_merged_full = src3.merge_by_email(df_gm_y_df_ca, df_naics_o, "correo", "Email Address", "FULL NAME", "Name_N")
print(df_merged_full[["Clean_Name","FULL NAME","Phone","telefono","score"]].head())

               Clean_Name               FULL NAME  \
0  lutgardo acevedo lopez  lutgardo acevedo lopez
1        edil quiles seda        edil quiles seda
2       omar bonet tirado       omar bonet tirado
3       onix cintron baez       onix cintron baez
4     beatriz cay vazquez     beatriz cay vazquez

                         Email                       correo  score
0        lacevedolaw@gmail.com        lacevedolaw@gmail.com    1.0
1       quilesseda@hotmail.com       quilesseda@hotmail.com    1.0
2          omar.bonet@capr.org          omar.bonet@capr.org    1.0
3   onix.cintron.law@gmail.com   onix.cintron.law@gmail.com    1.0
4  beatrizcayvazquez@gmail.com  beatrizcayvazquez@gmail.com    1.0
Empty DataFrame
Columns: [Clean_Name, Name_N, Phone, phone, score]
Index: []
               FULL NAME                 Name_N                    correo  \
0   jose gonzalez rivera          jose gonzalez   jrg@gonzalezmorales.com
1  ricardo garcia negron  ricardo garcia negron             rjg@mcvpr.com
2   robert collins viera         robert collins           rtc@fclawpr.com
3   jose caceres cardona   jose caceres cardona  jfcaceres@caceresllc.com
4    pedro manzano yates    pedro manzano yates      pmanzano@scmplex.com

              Email Address     score
0   jrg@gonzalezmorales.com  0.787879
1             rjg@mcvpr.com  1.000000
2           rtc@fclawpr.com  0.823529
3  jfcaceres@caceresllc.com  1.000000
4      pmanzano@scmplex.com  1.000000
Empty DataFrame
Columns: [Clean_Name, FULL NAME, Phone, telefono, score]
Index: []

# Coincidencias exactas por Nombre

In [ ]:
#Merge entre gm y ca    -->> ** 5 coincidencias exactas **
df_gm_y_df_ca = src3.merge_by_email(df_gm_o, df_ca_o, "Clean_Name", "FULL NAME", "Clean_Name", "FULL NAME")
print(df_gm_y_df_ca[["Clean_Name","FULL NAME","score"]].head())

#Merge entre gm y naics -->> ** 5 coincidencias exactas **
df_gm_y_df_naics = src3.merge_by_email(df_gm_o, df_naics_o, "Clean_Name", "Name_N", "Clean_Name", "Name_N")
print(df_gm_y_df_naics[["Clean_Name","Name_N","score"]].head())

#Merge entre ca y naics  -->> ** 5 coincidencias exactas **
df_ca_y_df_naics = src3.merge_by_email(df_ca_o, df_naics_o, "FULL NAME", "Name_N", "FULL NAME", "Name_N")
print(df_ca_y_df_naics[["FULL NAME","Name_N","score"]].head())               

#Merge COMPLETO   -->> NO HAY CONCIDENCIAS  
df_merged_full = src3.merge_by_email(df_gm_y_df_ca, df_naics_o, "Clean_Name", "Name_N", "FULL NAME", "Name_N")
print(df_merged_full[["Clean_Name","FULL NAME","score"]].head())

               Clean_Name               FULL NAME  score
0    luis mercado hidalgo    luis mercado hidalgo    1.0
1  lutgardo acevedo lopez  lutgardo acevedo lopez    1.0
2   jorge hernandez lopez   jorge hernandez lopez    1.0
3   angela oquendo negron   angela oquendo negron    1.0
4   manlio arraiza donate   manlio arraiza donate    1.0
         Clean_Name            Name_N  score
0  felipe sotoortiz  felipe sotoortiz    1.0
1     jaime ruberte     jaime ruberte    1.0
2   gilberto oliver   gilberto oliver    1.0
3      jose benitez      jose benitez    1.0
4   francisco ramos   francisco ramos    1.0
                      FULL NAME                        Name_N  score
0   veronica gonzalez rodriguez   veronica gonzalez rodriguez    1.0
1          edwin rivera cintron          edwin rivera cintron    1.0
2             alba lopez arzola             alba lopez arzola    1.0
3       isabel ruberte figueroa       isabel ruberte figueroa    1.0
4  isamillie melendez caraballo  isamillie melendez caraballo    1.0
Empty DataFrame
Columns: [Clean_Name, FULL NAME, score]
Index: []

# Merge por coincidencias difusas de nombre

In [41]:
df_gm = df_gm_o[["Clean_Name"]]
df_ca = df_ca_o[["FULL NAME"]]
df_naics = df_naics_o[["Name_N"]]

In [42]:
matches = src.find_fuzzy_matches(df_ca, df_naics,"FULL NAME", "Name_N", 76)

In [43]:
evaluacion = src4.test(matches)

In [44]:
#evaluacion = src4.test_v2(matches)

In [45]:
from sklearn.metrics import confusion_matrix, f1_score

# Suponiendo que tienes:
y_true = evaluacion["actual"]
y_pred = evaluacion["predicted"]

# Confusion matrix
tn, fp, fn, tp = confusion_matrix(y_true, y_pred).ravel()

# F1-score
f1 = f1_score(y_true, y_pred)

# Mostrar resultados
print(f"TP: {tp}")
print(f"TN: {tn}")
print(f"FP: {fp}")
print(f"FN: {fn}")
print(f"F1-score: {f1:.2f}")

TP: 207
TN: 2157
FP: 34
FN: 293
F1-score: 0.56

In [55]:
final = evaluacion[evaluacion["predicted"] == 1]
final.reset_index(drop=True, inplace=True)
final.to_csv()

',name1,name2,score,actual,predicted\n0,ruben lucena quiles,ruben lucena,77.41935483870968,1,1\n1,jose bague soto,jose soto,75.0,0,1\n2,veronica gonzalez rodriguez,veronica gonzalez rodriguez,100.0,1,1\n3,rosa corrada colon,rosa corrada,80.0,1,1\n4,edwin rivera cintron,edwin rivera cintron,100.0,1,1\n5,luisselle quinones maldonado,luisselle quinones,78.26086956521739,1,1\n6,alba lopez arzola,alba lopez arzola,100.0,1,1\n7,jose gonzalez rivera,jose gonzalez,78.78787878787878,1,1\n8,antonio bauza santos,antonio santos,82.35294117647058,1,1\n9,carlos torres velez,carlos velez,77.41935483870968,1,1\n10,jose gonzalez jimenez,jose gonzalez,76.47058823529412,1,1\n11,francisco rodriguez bernier,francisco rodriguez,82.6086956521739,1,1\n12,jose belen rivera,jose rivera,78.57142857142857,1,1\n13,angel flores rivera,angel flores,77.41935483870968,1,1\n14,melissa pellicier ortiz,melissa ortiz,72.22222222222221,0,1\n15,isabel ruberte figueroa,isabel ruberte figueroa,100.0,1,1\n16,isamillie melendez caraballo,isamillie melendez caraballo,100.0,1,1\n17,antonio plaza plaza,antonio plaza plaza,100.0,1,1\n18,yamilee sepulveda arroyo,yamilee sepulveda,82.92682926829268,1,1\n19,jean perez figueroa,jean perez,68.96551724137932,0,1\n20,jose santana gonzalez,jose gonzalez,76.47058823529412,1,1\n21,ricardo garcia negron,ricardo garcia negron,100.0,1,1\n22,jose melendez alfonzo,jose melendez alfonzo,100.0,1,1\n23,marisol medina velazquez,marisol velazquez,82.92682926829268,1,1\n24,francisco santiago rodriguez,francisco rodriguez,80.85106382978724,1,1\n25,robert collins viera,robert collins,82.35294117647058,1,1\n26,solymar castillo morales,solymar castillo,80.0,1,1\n27,jose caceres cardona,jose caceres cardona,100.0,1,1\n28,edgardo rivera rivera,edgardo rivera rivera,100.0,1,1\n29,maria raimundi melendez,maria melendez,75.67567567567568,0,1\n30,jose alvarado vazquez,jose vazquez,72.72727272727273,0,1\n31,carlos caban rodriguez,carlos rodriguez,84.21052631578947,1,1\n32,fernando sabater clavell,fernando sabater,80.0,1,1\n33,yolanda alvarez cruz,yolanda alvarez,85.71428571428572,1,1\n34,yadira colon alicea,yadira colon alicea,100.0,1,1\n35,maricely aponte rivera,maricely aponte rivera,100.0,1,1\n36,magdalis prats figueroa,magdalis prats figueroa,100.0,1,1\n37,jorge tantao echevarria,jorge tantao echevarria,100.0,1,1\n38,josue castellanos otero,josue emanuel castellanos otero,85.18518518518519,1,1\n39,gabriela rivera negron,gabriela rivera,81.08108108108108,1,1\n40,frank gonzalez acevedo,frank gonzalez,77.77777777777779,1,1\n41,jose gonzalez ortiz,jose gonzalez,81.25,1,1\n42,alberto perez hernandez,alberto perez hernandez,100.0,1,1\n43,vanessa blanco mendez,vanessa blanco,80.0,1,1\n44,jose toro iturrino,jose toro,66.66666666666667,0,1\n45,angel matos flores,angel flores,80.0,1,1\n46,hiram lozada perez,hiram lozada,80.0,1,1\n47,julio montalvo melendez,julio montalvo,75.67567567567568,0,1\n48,jose rivera cordero,jose rivera,73.33333333333334,0,1\n49,luis perez giusti,luis perez giusti,100.0,1,1\n50,jose gonzalez villamil,jose gonzalez,74.28571428571429,0,1\n51,astrid soto lopez,astrid soto,78.57142857142857,1,1\n52,ricardo agrait defillo,ricardo agrait defillo,100.0,1,1\n53,xiomara torres guzman,xiomara guzman,80.0,1,1\n54,mariana bula lopez,mariana lopez,83.87096774193549,1,1\n55,pedro manzano yates,pedro manzano yates,100.0,1,1\n56,daniel quiles pumarejo,daniel quiles,74.28571428571429,0,1\n57,myrna rodriguez rodriguez,myrna rodriguez rodriguez,100.0,1,1\n58,jose rosa crespo,jose rosa,72.0,0,1\n59,hector santiago gomez,hector santiago,83.33333333333334,1,1\n60,melba acosta febo,melba acosta,82.75862068965517,1,1\n61,jose quinones lopez,jose alberto quinones lopez,82.6086956521739,1,1\n62,david magraner ortiz,david magraner,82.35294117647058,1,1\n63,magda boyles pont,magda boyles pont,100.0,1,1\n64,francisco garcia garcia,francisco garcia,82.05128205128204,1,1\n65,manuel amill cintron,manuel amill,75.0,0,1\n66,guardin sosa rojas,guardin sosa,80.0,1,1\n67,salvador jimenez santoni,salvador jimenez santoni,100.0,1,1\n68,cesar rosario vega,cesar rosario,83.87096774193549,1,1\n69,samuel cespedes sabater,samuel cespedes sabater,100.0,1,1\n70,maria gonzalez calderon,maria elena gonzalez calderon,88.46153846153845,1,1\n71,celimar gracia marin,celimar gracia,82.35294117647058,1,1\n72,manuel mayo lopez,manuel lopez,82.75862068965517,1,1\n73,carlos rodriguez cruz,carlos rodriguez,86.48648648648648,1,1\n74,glorimar acevedo cruz,glorimar acevedo cruz,100.0,1,1\n75,arcelio maldonado aviles,arcelio maldonado,82.92682926829268,1,1\n76,jose martinez chevres,jose martinez,76.47058823529412,1,1\n77,mariel soto irizarry,mariel soto irizarry,100.0,1,1\n78,rafael garcia lopez,rafael garcia lopez,100.0,1,1\n79,sonia torres cartagena,sonia torres,70.58823529411764,0,1\n80,karen ocasio vazquez,karen ocasio,75.0,0,1\n81,xana connelly pagan,xana connelly,81.25,1,1\n82,stephanie perez mangual,stephanie perez,78.94736842105263,1,1\n83,guillermo figueroa navarro,guillermo figueroa navarro,100.0,1,1\n84,luis dueno vargas,luis vargas,78.57142857142857,1,1\n85,griselle arbona martinez,griselle arbona,76.92307692307692,1,1\n86,carlos bermudez monroig,carlos bermudez,78.94736842105263,1,1\n87,jose franco gomez,jose franco,78.57142857142857,1,1\n88,luis rivera leon,luis rivera,81.4814814814815,1,1\n89,alberto morales rodriguez,alberto rodriguez,80.95238095238095,1,1\n90,javier morales ramos,javier morales,82.35294117647058,1,1\n91,jose guzman rosario,jose rosario,77.41935483870968,1,1\n92,alfredo nigaglioni santiago,alfredo nigaglioni santiago,100.0,1,1\n93,carlos rosario rivera,carlos rosario,80.0,1,1\n94,samuel padua vazquez,samuel padua,75.0,0,1\n95,leishla agosto ortiz,leishla agosto,82.35294117647058,1,1\n96,monica agosto pineiro,monica agosto pineiro,100.0,1,1\n97,cesar alcover acosta,cesar alcover,78.78787878787878,1,1\n98,juan alvarez valentin,juan alvarez valentin,100.0,1,1\n99,juan ayala acevedo,juan acevedo,80.0,1,1\n100,grisselle bermudez rodriguez,grisselle bermudez,78.26086956521739,1,1\n101,cecille blondet passalacqua,cecille blondet,71.42857142857143,0,1\n102,roberto bolorin santiago,roberto santiago,80.0,1,1\n103,heriberto burgos perez,heriberto burgos,84.21052631578947,1,1\n104,nikos buxeda ferrer,nikos buxeda,77.41935483870968,1,1\n105,karyna cabrera toledo,karyna cabrera toledo,100.0,1,1\n106,ursula carrion nevarez,ursula carrion nevarez,100.0,1,1\n107,maria cartagena cancel,maria cartagena cancel,100.0,1,1\n108,ricardo casellas sanchez,ricardo casellas,80.0,1,1\n109,salvador casellas toro,salvador casellas,87.17948717948718,1,1\n110,aniris castellano guzman,aniris castellano,82.92682926829268,1,1\n111,raul castellanos malave,raul castellanos,82.05128205128204,1,1\n112,wanda castro aleman,wanda castro,77.41935483870968,1,1\n113,samuel cespedes,samuel cespedes,100.0,1,1\n114,jose chacon soto,jose soto,72.0,0,1\n115,andres colberg trigo,andres colberg,82.35294117647058,1,1\n116,yeidalis collazo salgado,yeidalis collazo salgado,100.0,1,1\n117,jose coll diaz,jose diaz,78.26086956521739,1,1\n118,manuel colon cabrera,manuel colon,75.0,0,1\n119,francisco colon pagan,francisco colon,83.33333333333334,1,1\n120,francisco colon ramirez,francisco colon,78.94736842105263,1,1\n121,yahaira colon rodriguez,yahaira colon rodriguez,100.0,1,1\n122,aura colon sola,aura colon sola,100.0,1,1\n123,rene comas perez,rene comas,76.92307692307692,1,1\n124,lillianette cortes soto,lillianette cortes,87.8048780487805,1,1\n125,coralys cruz perez,coralys cruz perez,100.0,1,1\n126,rebecca cuevas fontan,rebecca cuevas,80.0,1,1\n127,angelica curbelo rosa,angelica curbelo rosa,100.0,1,1\n128,yahaira de la rosa algarin,yahaira de la rosa algarin,100.0,1,1\n129,marta diaz pietri,marta pietri,82.75862068965517,1,1\n130,ricardo diaz soto,ricardo diaz soto,100.0,1,1\n131,maria diez rodriguez,maria gabriela diez rodriguez,81.63265306122449,1,1\n132,jose figueroa gonzalez,jose gonzalez,74.28571428571429,0,1\n133,enrique figueroa llinas,enrique figueroa llinas,100.0,1,1\n134,leslie flores rodriguez,leslie flores,72.22222222222221,0,1\n135,jose garcia baez,jose garcia,81.4814814814815,1,1\n136,jose garcia soto,jose garcia,81.4814814814815,1,1\n137,claribel gascot nieves,claribel gascot nieves,100.0,1,1\n138,pablo gil diaz,pablo gil,78.26086956521739,1,1\n139,jose gonzalez bonilla,jose gonzalez,76.47058823529412,1,1\n140,jorge gonzalez rodriguez,jorge rodriguez,76.92307692307692,1,1\n141,janine guzman correa,janine guzman,78.78787878787878,1,1\n142,arturo hernandez gonzalez,arturo hernandez,78.04878048780488,1,1\n143,jorge hernandez gonzalez,jorge hernandez,76.92307692307692,1,1\n144,jorge hernandez lopez,jorge hernandez,83.33333333333334,1,1\n145,jose jimenez rivera,jose rivera,73.33333333333334,0,1\n146,antonio jusino rodriguez,antonio rodriguez,82.92682926829268,1,1\n147,natalia kerr giannoni,natalia kerr,72.72727272727273,0,1\n148,hector laffitte colomer,hector laffitte,78.94736842105263,1,1\n149,steven lausell recurt,steven lausell,80.0,1,1\n150,madeleine llovet otero,madeleine llovet,84.21052631578947,1,1\n151,mariana lopez baez,mariana lopez,83.87096774193549,1,1\n152,rica lopez de alos,rica lopez de alos,100.0,1,1\n153,ivette lopez figueroa,ivette lopez,72.72727272727273,0,1\n154,manuel lopez gay,manuel lopez,85.71428571428572,1,1\n155,julio lopez keelan,julio lopez keelan,100.0,1,1\n156,nestor lo presti reyes,nestor lo presti reyes,100.0,1,1\n157,yolanda machado torres,yolanda machado torres,100.0,1,1\n158,ivan maraver marrero,ivan marrero,75.0,0,1\n159,francisco marin rodriguez,francisco rodriguez,86.36363636363636,1,1\n160,juan martinez rodriguez,juan rodriguez,75.67567567567568,0,1\n161,lissette medina muniz,lissette medina,83.33333333333334,1,1\n162,nayla melamed torres,nayla melamed torres,100.0,1,1\n163,tatiana melendez garcia,tatiana melendez garcia,100.0,1,1\n164,ruben mendez benabe,ruben mendez,77.41935483870968,1,1\n165,guimazoa miranda hernandez,guimazoa miranda hernandez,100.0,1,1\n166,silvestre miranda,silvestre miranda,100.0,1,1\n167,luis molina rivera,luis rivera,75.86206896551724,0,1\n168,jose monroy gonzalez,jose gonzalez,78.78787878787878,1,1\n169,joaquin monserrate matienzo,joaquin monserrate,80.0,1,1\n170,jaime munoz salas,jaime munoz salas,100.0,1,1\n171,rafael munoz valle,rafael valle,80.0,1,1\n172,luis negron cacho,luis negron,78.57142857142857,1,1\n173,jose negron fernandez,jose negron fernandez,100.0,1,1\n174,james noel iii,james noel,83.33333333333334,1,1\n175,jose oliveras gonzalez,jose gonzalez,74.28571428571429,0,1\n176,patrick neill cheyney,patrick neill,76.47058823529412,1,1\n177,maria ortiz collazo,maria ortiz,73.33333333333334,0,1\n178,miriam ortiz gonzalez,miriam ortiz gonzalez,100.0,1,1\n179,tatiana ortiz rivera,tatiana ortiz,78.78787878787878,1,1\n180,edwin otero morales,edwin otero morales,100.0,1,1\n181,pedro padilla torres,pedro torres,75.0,0,1\n182,andre palerm colon,andre palerm colon,100.0,1,1\n183,luis palou balsa,luis palou,76.92307692307692,1,1\n184,francisco pavia sanchez,francisco pavia,78.94736842105263,1,1\n185,vera penagaricano kindratiw,vera penagaricano,77.27272727272727,1,1\n186,dora penagaricano suarez,dora penagaricano,82.92682926829268,1,1\n187,wanda perez colon,wanda colon,78.57142857142857,1,1\n188,jose perez martinez,jose martinez,81.25,1,1\n189,maribel perez mora,maribel perez,83.87096774193549,1,1\n190,jarrette perez rodriguez,jarrette marie perez rodriguez,88.88888888888889,1,1\n191,roberto prats palerm,roberto prats palerm,100.0,1,1\n192,mario quiles rosado,mario quiles,77.41935483870968,1,1\n193,cristina quiles torres,cristina quiles,81.08108108108108,1,1\n194,antonio ramirez aponte,antonio ramirez,81.08108108108108,1,1\n195,rafael ramirez ball,rafael ramirez ball,100.0,1,1\n196,olga ramos carrasquillo,olga carrasquillo,85.0,1,1\n197,jorge rexach vaquer,jorge rexach vaquer,100.0,1,1\n198,jose rios gonzalez,jose gonzalez,83.87096774193549,1,1\n199,yelitza rivera aponte,yelitza rivera aponte,100.0,1,1\n200,giancarlo rivera cabrera,giancarlo rivera cabrera,100.0,1,1\n201,adalberto rivera perez,adalberto rivera rivera,84.44444444444444,1,1\n202,gavino rivera ramos,gavino rivera ramos,100.0,1,1\n203,jorge rodriguez colon,jorge rodriguez,83.33333333333334,1,1\n204,carlos rodriguez garcia,carlos rodriguez,82.05128205128204,1,1\n205,ivette rodriguez hernandez,ivette rodriguez,76.19047619047619,1,1\n206,lisandra rodriguez moreno,lisandra rodriguez moreno,100.0,1,1\n207,pedro rodriguez vazquez,pedro vazquez,72.22222222222221,0,1\n208,carlos rodriguez vidal,carlos rodriguez vidal,100.0,1,1\n209,jose rolon rivera,jose rivera,78.57142857142857,1,1\n210,joel roman roman,joel roman roman,100.0,1,1\n211,maribel rosario santiago,maribel rosario,76.92307692307692,1,1\n212,mildred rosa rivera,mildred rivera,84.84848484848484,1,1\n213,jose rovira rullan,jose rovira,75.86206896551724,0,1\n214,pedro rubero rivera,pedro rivera,77.41935483870968,1,1\n215,jaime ruberte santiago,jaime ruberte,74.28571428571429,0,1\n216,jaime sanabria montanez,jaime sanabria montanez,100.0,1,1\n217,sergio sanchez pagan,sergio sanchez,82.35294117647058,1,1\n218,devin santana torres,devin santana torres,100.0,1,1\n219,anthony santa rivera,anthony santa rivera,100.0,1,1\n220,mayleen santiago garces,mayleen santiago,82.05128205128204,1,1\n221,carlos santiago rivera,carlos santiago,81.08108108108108,1,1\n222,carlos santini rodriguez,carlos rodriguez,80.0,1,1\n223,manuel sarmiento vallecillo,manuel sarmiento,74.4186046511628,0,1\n224,karen scalley rivera,karen scalley,78.78787878787878,1,1\n225,jose soto,jose soto,100.0,1,1\n226,dalina sumner burgos,dalina sumner,78.78787878787878,1,1\n227,kenneth suria rivera,kenneth suria,78.78787878787878,1,1\n228,arianaliz torres cruz,arianaliz torres cruz,100.0,1,1\n229,janelise torres marrero,janelise torres marrero,100.0,1,1\n230,yarimar torres rodriguez,yarimar torres rodriguez,100.0,1,1\n231,pedro torres torres,pedro torres,77.41935483870968,1,1\n232,thomas trebilcock horan,thomas trebilcock,85.0,1,1\n233,enrique umpierre suarez ii,enrique umpierre suarez,93.87755102040816,1,1\n234,fernando van derdys,fernando van derdys,100.0,1,1\n235,maria vargas perez,maria perez,75.86206896551724,0,1\n236,jaime vazquez bernier,jaime vazquez,76.47058823529412,1,1\n237,rafael velazquez villares,rafael velazquez,78.04878048780488,1,1\n238,sonia velez colon,sonia colon,78.57142857142857,1,1\n239,elba villalba ojeda,elba villalba,81.25,1,1\n240,jose villamarzo santiago,jose villamarzo santiago,100.0,1,1\n'

In [57]:
final.head()

,name1,name2,score,actual,predicted
0,ruben lucena quiles,ruben lucena,77.419355,1,1
1,jose bague soto,jose soto,75.000000,0,1
2,veronica gonzalez rodriguez,veronica gonzalez rodriguez,100.000000,1,1
3,rosa corrada colon,rosa corrada,80.000000,1,1
4,edwin rivera cintron,edwin rivera cintron,100.000000,1,1

In [60]:
final["name2"].duplicated().any()
final[final["name2"].duplicated(keep=False)]

,name1,name2,score,actual,predicted
1,jose bague soto,jose soto,75.000000,0,1
7,jose gonzalez rivera,jose gonzalez,78.787879,1,1
10,jose gonzalez jimenez,jose gonzalez,76.470588,1,1
11,francisco rodriguez bernier,francisco rodriguez,82.608696,1,1
12,jose belen rivera,jose rivera,78.571429,1,1
13,angel flores rivera,angel flores,77.419355,1,1
20,jose santana gonzalez,jose gonzalez,76.470588,1,1
24,francisco santiago rodriguez,francisco rodriguez,80.851064,1,1
31,carlos caban rodriguez,carlos rodriguez,84.210526,1,1
41,jose gonzalez ortiz,jose gonzalez,81.250000,1,1
45,angel matos flores,angel flores,80.000000,1,1
48,jose rivera cordero,jose rivera,73.333333,0,1
50,jose gonzalez villamil,jose gonzalez,74.285714,0,1
54,mariana bula lopez,mariana lopez,83.870968,1,1
72,manuel mayo lopez,manuel lopez,82.758621,1,1
73,carlos rodriguez cruz,carlos rodriguez,86.486486,1,1
76,jose martinez chevres,jose martinez,76.470588,1,1
88,luis rivera leon,luis rivera,81.481481,1,1
114,jose chacon soto,jose soto,72.000000,0,1
119,francisco colon pagan,francisco colon,83.333333,1,1
120,francisco colon ramirez,francisco colon,78.947368,1,1
132,jose figueroa gonzalez,jose gonzalez,74.285714,0,1
135,jose garcia baez,jose garcia,81.481481,1,1
136,jose garcia soto,jose garcia,81.481481,1,1
139,jose gonzalez bonilla,jose gonzalez,76.470588,1,1
140,jorge gonzalez rodriguez,jorge rodriguez,76.923077,1,1
143,jorge hernandez gonzalez,jorge hernandez,76.923077,1,1
144,jorge hernandez lopez,jorge hernandez,83.333333,1,1
145,jose jimenez rivera,jose rivera,73.333333,0,1
151,mariana lopez baez,mariana lopez,83.870968,1,1
154,manuel lopez gay,manuel lopez,85.714286,1,1
159,francisco marin rodriguez,francisco rodriguez,86.363636,1,1
167,luis molina rivera,luis rivera,75.862069,0,1
168,jose monroy gonzalez,jose gonzalez,78.787879,1,1
175,jose oliveras gonzalez,jose gonzalez,74.285714,0,1
181,pedro padilla torres,pedro torres,75.000000,0,1
188,jose perez martinez,jose martinez,81.250000,1,1
198,jose rios gonzalez,jose gonzalez,83.870968,1,1
203,jorge rodriguez colon,jorge rodriguez,83.333333,1,1
204,carlos rodriguez garcia,carlos rodriguez,82.051282,1,1
209,jose rolon rivera,jose rivera,78.571429,1,1
222,carlos santini rodriguez,carlos rodriguez,80.000000,1,1
225,jose soto,jose soto,100.000000,1,1
231,pedro torres torres,pedro torres,77.419355,1,1