In [1]:
import pandas as pd
import numpy as np
from rapidfuzz.fuzz import ratio
import re
import src_any_abogados_fuzzymerge_df_er_v1_sec as src
import src_any_abogados_numbersmerge_df_er_v1_sec as src2
import src_any_abogados_emailmerge_df_er_v1_sec as src3
import src_any_abogados_test_df_er_v1_sec as src4

In [2]:
pd.set_option("display.max_rows", None)

In [3]:
def remove_empty_columns(df):

    df_aux = df.copy()
    empty_columns = list(df_aux.columns[df_aux.isna().mean() == 1])   # Almacena en una lista las columnas que están totalmente vacias
    if "Unnamed: 0" in df_aux.columns:
        empty_columns.append("Unnamed: 0")
    df_aux = df_aux.drop(columns=empty_columns)
    return df_aux

In [4]:
#Lectura de tablas
df_gm_o = pd.read_csv("datasets/Dataset_GM_PR.csv")
df_ca_o = pd.read_csv("datasets/datos_abogados.csv") 
df_naics_o = pd.read_csv("datasets/NAICS_Puerto Rico.csv")

df_gm_o = remove_empty_columns(df_gm_o)
df_ca_o = remove_empty_columns(df_ca_o)
df_naics_o = remove_empty_columns(df_naics_o)

df_gm_o["Email"] = df_gm_o["Email"].str.strip().replace(["Not available"], np.nan)

# Agregar columna que indique de dónde viene el registro
df_gm_o["dataset"] = "gm"
df_ca_o["dataset"] = "ca"
df_naics_o["dataset"] = "naics"

In [5]:
df_naics_o[df_naics_o["Name_N"] == "nestor lo presti reyes"]
df_ca_o[df_ca_o["FULL NAME"] == "nestor lo presti reyes"]

Empty DataFrame
Columns: [FULL NAME, FNAME, LNAME, colegiacion, rua, correo, tel_residencial, tel_oficina, tel_celular, otro, especialidades, Practice Area, delegacion, State, dataset]
Index: []

In [6]:
#Agregar columna "is Firm" para diferenciar Firma de Abogados
df_gm_o['is Firm'] = df_gm_o['Name'].apply(lambda x: bool(re.search(src.pattern_firma, str(x), flags=re.IGNORECASE)))

In [7]:
len(df_gm_o)

1496

In [8]:
#DataFrame que almacena los registros que son firmas
df_gm_firmas = df_gm_o[df_gm_o["is Firm"]]

#DataFrame filtrado y almacena los registro que son abogados
df_gm_o = df_gm_o[~df_gm_o["is Firm"]]

#Normalización de nombres
df_gm_o["Clean_Name"] = df_gm_o["Name"].apply(lambda x: src.name_normalized(x)).str.lower()
df_ca_o["FULL NAME"] = df_ca_o["FULL NAME"].apply(lambda x: src.name_normalized(x)).str.lower()
df_naics_o["Name_N"] = df_naics_o["Name_N"].apply(lambda x: src.name_normalized(x)).str.lower()

#Reset index
df_gm_o = df_gm_o.reset_index(drop=True)
df_ca_o = df_ca_o.reset_index(drop=True)
df_naics_o = df_naics_o.reset_index(drop=True)

In [9]:
len(df_gm_o)

698

In [10]:
# Columnas importantes: Name, city, state_name, Address, Website,Phone,Google_category,Type,Email,Specialization,Education,ExperiencE
# Columnas a Analizar: zip, state_id, Orig Specialization
# NO Columnas importantes: Google_URL, population,Google_rank,Google_opinions,Google_category,Processed,Name AI

#df_gm_o.isna().mean()

In [11]:
# Columnas importantes: FULL NAME', 'FNAME', 'LNAME
# Columnas a Analizar: 
# NO Columnas importantes:

#df_ca_o.isna().mean()

In [12]:
# Columnas importantes: FULL NAME', 'FNAME', 'LNAME
# Columnas a Analizar: 
# NO Columnas importantes:

#df_naics_o.isna().mean()

In [13]:
df_ca_o = src2.combine_columns_by_priority(df_ca_o,["tel_celular","tel_residencial","tel_oficina","otro"],"telefono")
df_naics_o = src2.combine_columns_by_priority(df_naics_o,["Mobile phone","Direct Phone Number"], "phone")

In [14]:
df_ca_o["telefono"] = df_ca_o["telefono"].apply(lambda phone: src2.normalized_phone(str(phone)) if pd.notnull(phone) else None)
df_naics_o["phone"] = df_naics_o["Mobile phone"].apply(lambda phone: src2.normalized_phone(str(phone)) if pd.notnull(phone) else None)

# Merge por coincidencia exacta de número de contacto

No se obtuvo ninguna coincidencia exacta por número de teléfono entre los 3 datasets.
Se obtuvo 3 coincidencias exactas entre los datasets del colegio de abogados y naics

In [15]:
#Merge entre gm y ca
df_gm_y_df_ca = src2.merge_by_contact_number(df_gm_o, df_ca_o, "Phone", "telefono", "Clean_Name", "FULL NAME")
print(df_gm_y_df_ca[["Clean_Name","FULL NAME","Phone","telefono","score"]].head())

                Clean_Name                FULL NAME    Phone telefono  score
0     luis mercado hidalgo     luis mercado hidalgo  4537437  4537437      1
1   lutgardo acevedo lopez   lutgardo acevedo lopez  4669845  4669845      1
2         edil quiles seda         edil quiles seda  8962727  8962727      1
3  lizandra torres rosario  lizandra torres rosario  6392632  6392632      1
4  vanessa gordils vazquez  vanessa gordils vazquez  8085036  8085036      1

In [16]:
#Merge entre gm y naics
df_gm_y_df_naics = src2.merge_by_contact_number(df_gm_o, df_naics_o, "Phone", "phone", "Clean_Name", "Name_N")
print(df_gm_y_df_naics[["Clean_Name","Name_N","Phone","phone","score"]].head())

               Clean_Name                  Name_N    Phone    phone  score
0       tus documentos pr    roberto velez medina  8507164  8507164      0
1  julian rivera aspinall  julian rivera aspinall  3600094  3600094      1
2         carlos lamoutte         carlos lamoutte  6886036  6886036      1

In [17]:
#Merge entre ca y naics  -->> **  # Salen 3 registros coincidencia exacta **
df_ca_y_df_naics = src2.merge_by_contact_number(df_ca_o, df_naics_o, "telefono", "phone", "FULL NAME", "Name_N")
print(df_ca_y_df_naics[["FULL NAME","Name_N","telefono","phone","score"]].head())

                 FULL NAME                           Name_N telefono    phone  \
0     esteban mujica cotto              esteban mujicacotto  5184101  5184101
1  josue castellanos otero  josue emanuel castellanos otero  2995935  2995935
2  francisco garcia garcia                 francisco garcia  3984898  3984898

   score
0      0
1      0
2      0

In [ ]:
#Merge COMPLETO
df_merged_full = src2.merge_by_contact_number(df_gm_y_df_ca, df_naics_o, "Phone", "phone", "FULL NAME", "Name_N")
print(df_merged_full[["Clean_Name","FULL NAME","Phone","telefono","score"]].head())

Empty DataFrame
Columns: [Clean_Name, FULL NAME, Phone, telefono, score]
Index: []

:

# Merge por coincidencia exacta de Email

In [ ]:
#Merge entre gm y ca    -->> ** 5 coincidencias exactas **
df_gm_y_df_ca = src3.merge_by_email(df_gm_o, df_ca_o, "Email", "correo", "Clean_Name", "FULL NAME")
print(df_gm_y_df_ca[["Clean_Name","FULL NAME","Email","correo","score"]].head())

#Merge entre gm y naics -->> NO COINCIDENCIAS
df_gm_y_df_naics = src3.merge_by_email(df_gm_o, df_naics_o, "Email", "Email Address", "Clean_Name", "Name_N")
print(df_gm_y_df_naics[["Clean_Name","Name_N","Phone","phone","score"]].head())

#Merge entre ca y naics  -->> ** 5 coincidencias exactas
df_ca_y_df_naics = src3.merge_by_email(df_ca_o, df_naics_o, "correo", "Email Address", "FULL NAME", "Name_N")
print(df_ca_y_df_naics[["FULL NAME","Name_N","correo","Email Address","score"]].head())               

#Merge COMPLETO   -->> NO COINCIDENCIAS
df_merged_full = src3.merge_by_email(df_gm_y_df_ca, df_naics_o, "correo", "Email Address", "FULL NAME", "Name_N")
print(df_merged_full[["Clean_Name","FULL NAME","Phone","telefono","score"]].head())

                          Clean_Name                 FULL NAME Email correo  \
0  angel egozcue de quiebras arecibo     maria barrera rosario   NaN    NaN
1  angel egozcue de quiebras arecibo     martha berrios rivera   NaN    NaN
2  angel egozcue de quiebras arecibo    yolanda castro borrero   NaN    NaN
3  angel egozcue de quiebras arecibo  catherine catala lasanta   NaN    NaN
4  angel egozcue de quiebras arecibo      luis del valle colon   NaN    NaN

      score
0  0.370370
1  0.333333
2  0.363636
3  0.315789
4  0.377358
                          Clean_Name                          Name_N  \
0  angel egozcue de quiebras arecibo                    larry suckle
1  angel egozcue de quiebras arecibo  alex giovanni rodriguez negron
2  angel egozcue de quiebras arecibo                 aura colon sola
3  angel egozcue de quiebras arecibo                       joe mehra
4  angel egozcue de quiebras arecibo                     judy arroyo

             Phone    phone     score
0  +1 787-881-8284     None  0.177778
1  +1 787-881-8284     None  0.380952
2  +1 787-881-8284     None  0.291667
3  +1 787-881-8284  4371032  0.285714
4  +1 787-881-8284     None  0.272727
               FULL NAME                          Name_N correo Email Address  \
0  maria barrera rosario                    larry suckle    NaN           NaN
1  maria barrera rosario  alex giovanni rodriguez negron    NaN           NaN
2  maria barrera rosario                 aura colon sola    NaN           NaN
3  maria barrera rosario                       joe mehra    NaN           NaN
4  maria barrera rosario                     judy arroyo    NaN           NaN

      score
0  0.303030
1  0.392157
2  0.388889
3  0.266667
4  0.375000

# Coincidencias exactas por Nombre

In [ ]:
#Merge entre gm y ca    -->> ** 5 coincidencias exactas **
df_gm_y_df_ca = src3.merge_by_email(df_gm_o, df_ca_o, "Clean_Name", "FULL NAME", "Clean_Name", "FULL NAME")
print(df_gm_y_df_ca[["Clean_Name","FULL NAME","score"]].head())

#Merge entre gm y naics -->> ** 5 coincidencias exactas **
df_gm_y_df_naics = src3.merge_by_email(df_gm_o, df_naics_o, "Clean_Name", "Name_N", "Clean_Name", "Name_N")
print(df_gm_y_df_naics[["Clean_Name","Name_N","score"]].head())

#Merge entre ca y naics  -->> ** 5 coincidencias exactas **
df_ca_y_df_naics = src3.merge_by_email(df_ca_o, df_naics_o, "FULL NAME", "Name_N", "FULL NAME", "Name_N")
print(df_ca_y_df_naics[["FULL NAME","Name_N","score"]].head())               

#Merge COMPLETO   -->> NO HAY CONCIDENCIAS  
df_merged_full = src3.merge_by_email(df_gm_y_df_ca, df_naics_o, "Clean_Name", "Name_N", "FULL NAME", "Name_N")
print(df_merged_full[["Clean_Name","FULL NAME","score"]].head())

               Clean_Name               FULL NAME  score
0    luis mercado hidalgo    luis mercado hidalgo    1.0
1  lutgardo acevedo lopez  lutgardo acevedo lopez    1.0
2   jorge hernandez lopez   jorge hernandez lopez    1.0
3   angela oquendo negron   angela oquendo negron    1.0
4   manlio arraiza donate   manlio arraiza donate    1.0
         Clean_Name            Name_N  score
0  felipe sotoortiz  felipe sotoortiz    1.0
1     jaime ruberte     jaime ruberte    1.0
2   gilberto oliver   gilberto oliver    1.0
3      jose benitez      jose benitez    1.0
4   francisco ramos   francisco ramos    1.0
                      FULL NAME                        Name_N  score
0   veronica gonzalez rodriguez   veronica gonzalez rodriguez    1.0
1          edwin rivera cintron          edwin rivera cintron    1.0
2             alba lopez arzola             alba lopez arzola    1.0
3       isabel ruberte figueroa       isabel ruberte figueroa    1.0
4  isamillie melendez caraballo  isamillie melendez caraballo    1.0
Empty DataFrame
Columns: [Clean_Name, FULL NAME, score]
Index: []

# Merge por coincidencias difusas de nombre

In [ ]:
df_gm = df_gm_o[["Clean_Name"]]
df_ca = df_ca_o[["FULL NAME"]]
df_naics = df_naics_o[["Name_N"]]

In [ ]:
matches = src.find_fuzzy_matches(df_ca, df_naics,"FULL NAME", "Name_N", 76)

In [ ]:
evaluacion = src4.test(matches)

In [ ]:
from sklearn.metrics import confusion_matrix, f1_score

# Suponiendo que tienes:
y_true = evaluacion["actual"]
y_pred = evaluacion["predicted"]

# Confusion matrix
tn, fp, fn, tp = confusion_matrix(y_true, y_pred).ravel()

# F1-score
f1 = f1_score(y_true, y_pred)

# Mostrar resultados
print(f"TP: {tp}")
print(f"TN: {tn}")
print(f"FP: {fp}")
print(f"FN: {fn}")
print(f"F1-score: {f1:.2f}")

TP: 185
TN: 799
FP: 24
FN: 155
F1-score: 0.67

In [ ]:
final = evaluacion[evaluacion["predicted"] == 1]
final.reset_index(drop=True, inplace=True)
final.to_csv("datasets/fuzz_merge.csv")

In [ ]:
final.head()

,name1,name2,score,actual,predicted
0,giancarlo rivera cabrera,giancarlo rivera cabrera,100.0,1,1
1,isamillie melendez caraballo,isamillie melendez caraballo,100.0,1,1
2,jose melendez alfonzo,jose melendez alfonzo,100.0,1,1
3,yeidalis collazo salgado,yeidalis collazo salgado,100.0,1,1
4,yelitza rivera aponte,yelitza rivera aponte,100.0,1,1

In [ ]:
#------------------------- PRUEBA CON ARCHIVOS DE CHATGPT --------------------------------#

In [ ]:
step1 = final.merge(df_ca_o, left_on="name1", right_on="FULL NAME", how="inner")
final_step = step1.merge(df_naics_o, left_on="name2", right_on="Name_N", how="inner")
columnas_principales = ["FULL NAME", "Name_N", "score","FNAME","LNAME"]
otras_columnas = [col for col in final_step.columns if col not in columnas_principales]
final_step = final_step[columnas_principales + otras_columnas]
final_step.drop(columns=["name1","name2","actual","predicted"], inplace=True)
final_step = final_step.rename(columns={
    "FULL NAME": "name_colegio_abogados",
    "Name_N": "name_naics"
})
final_step.to_csv("datasets/merge_colegio-abogados_naics.csv")
final_step

,name_colegio_abogados,name_naics,score,FNAME,LNAME,colegiacion,rua,correo,tel_residencial,tel_oficina,...,Company State,Company Zip Code,Company Country,Full Address,Number of Locations,Query Name,Subject 2 New,Body 2 New,dataset_y,phone
0,giancarlo rivera cabrera,giancarlo rivera cabrera,100.000000,Giancarlo,Rivera Cabrera,NaN,NaN,NaN,NaN,NaN,...,Puerto Rico,918,United States,"208 Ave Ponce De Leon Ste 1400, San Juan, Puer...",2.0,naics-541110puertorico,NaN,NaN,naics,None
1,isamillie melendez caraballo,isamillie melendez caraballo,100.000000,Isamillie,Melendez Caraballo,21361.0,22798.0,NaN,NaN,NaN,...,Puerto Rico,908,United States,"PO Box 9134, San Juan, Puerto Rico, 00908, Uni...",5.0,naics-541110puertorico,NaN,NaN,naics,None
2,jose melendez alfonzo,jose melendez alfonzo,100.000000,Jose,Melendez Alfonzo,17772.0,16519.0,NaN,NaN,NaN,...,Puerto Rico,901,United States,"150 Tetuan St, San Juan, Puerto Rico, 00901, U...",14.0,naics-541110puertorico,NaN,NaN,naics,None
3,yeidalis collazo salgado,yeidalis collazo salgado,100.000000,Yeidalis,Collazo Salgado,21458.0,23276.0,NaN,NaN,NaN,...,Puerto Rico,920,United States,"1647 Adams St, San Juan, Puerto Rico, 00920, U...",1.0,naics-541110puertorico,NaN,NaN,naics,None
4,yelitza rivera aponte,yelitza rivera aponte,100.000000,Yelitza,Rivera Aponte,21547.0,23714.0,NaN,NaN,NaN,...,Valencia,46002,Spain,"B · 1 1, Valencia, Valencia, 46002, Spain",4.0,naics-541110puertorico,NaN,NaN,naics,7876050182
5,edwin rivera cintron,edwin rivera cintron,100.000000,Edwin,Rivera Cintron,14332.0,13055.0,erclegal@yahoo.com,NaN,787-716-0618,...,NaN,NaN,United States,United States,NaN,naics-541110puertorico,NaN,NaN,naics,None
6,magda boyles pont,magda boyles pont,100.000000,Magda,Boyles Pont,18835.0,17560.0,NaN,NaN,NaN,...,Puerto Rico,918,United States,"270 Munoz Rivera, San Juan, Puerto Rico, 00918...",9.0,naics-541110puertorico,NaN,NaN,naics,7873546221
7,arianaliz torres cruz,arianaliz torres cruz,100.000000,Arianaliz,Torres Cruz,NaN,NaN,NaN,NaN,NaN,...,Puerto Rico,907,United States,"954 Ave Ponce De Leon Ste 201, San Juan, Puert...",1.0,naics-541110puertorico,NaN,NaN,naics,7879076310
8,jaime sanabria montanez,jaime sanabria montanez,100.000000,Jaime,Sanabria Montañez,15716.0,14260.0,NaN,NaN,NaN,...,Valencia,46002,Spain,"B · 1 1, Valencia, Valencia, 46002, Spain",4.0,naics-541110puertorico,NaN,NaN,naics,7875043004
9,isabel ruberte figueroa,isabel ruberte figueroa,100.000000,Isabel,Ruberte Figueroa,20449.0,21395.0,isabel.ruberte12@gmail.com,NaN,787-815-2680,...,Puerto Rico,908,United States,"PO Box 9134, San Juan, Puerto Rico, 00908, Uni...",5.0,naics-541110puertorico,NaN,NaN,naics,None
10,alfredo nigaglioni santiago,alfredo nigaglioni santiago,100.000000,Alfredo,Nigaglioni Santiago,21354.0,23295.0,lcdo.nigaglioni@gmail.com,NaN,NaN,...,Puerto Rico,928,United States,"PO Box 21490, San Juan, Puerto Rico, 00928, Un...",1.0,naics-541110puertorico,NaN,NaN,naics,None
11,yahaira de la rosa algarin,yahaira de la rosa algarin,100.000000,Yahaira,De La Rosa Algarin,19137.0,18061.0,NaN,NaN,NaN,...,Greater London,EC1A 4HT,United Kingdom,"160 Aldersgate St, London, Greater London, EC1...",127.0,naics-541110puertorico,NaN,NaN,naics,7872096659
12,jorge tantao echevarria,jorge tantao echevarria,100.000000,Jorge,Tantao Echevarria,8229.0,7068.0,NaN,NaN,NaN,...,Puerto Rico,908,United States,"PO Box 9134, San Juan, Puerto Rico, 00908, Uni...",5.0,naics-541110puertorico,NaN,NaN,naics,None
13,nestor lo presti reyes,nestor lo presti reyes,100.000000,Nestor,Lo Presti Reyes,17918.0,16692.0,NaN,NaN,NaN,...,Puerto Rico,918,United States,"208 Ponce De Leon Ave Ste 1600, San Juan, Puer...",2.0,naics-541110puertorico,NaN,NaN,naics,None
14,samuel cespedes,samuel cespedes,100.000000,Samuel,Cespedes,1912.0,2058.0,NaN,NaN,NaN,...,Puerto Rico,918,United States,"270 Munoz Rivera, San Juan, Puerto Rico, 00918...",9.0,naics-541110puertorico,NaN,NaN,naics,7875876432
15,magdalis prats figueroa,magdalis prats figueroa,100.000000,Magdalis,Prats Figueroa,21059.0,22287.0,NaN,NaN,NaN,...,Puerto Rico,918,United States,"250 Ave Munoz Rivera Ste 1500, San Juan, Puert...",2.0,naics-541110puertorico,NaN,NaN,naics,7873818334
16,joel roman roman,joel roman roman,100.000000,Joel,Roman Roman,16415.0,15306.0,NaN,NaN,NaN,...,Puerto Rico,928,United States,"PO Box 21490, San Juan, Puerto Rico, 00928, Un...",1.0,naics-541110puertorico,NaN,NaN,naics,None
17,mariel soto irizarry,mariel soto irizarry,100.000000,Mariel,Soto Irizarry,19293.0,18460.0,marielsotopr@yahoo.com,NaN,787-806-3600,...,NaN,NaN,United States,United States,NaN,naics-541110puertorico,NaN,NaN,naics,7876610153
18,ricardo garcia negron,ricardo garcia negron,100.000000,Ricardo,Garcia Negron,18963.0,17800.0,rjg@mcvpr.com,NaN,NaN,...,Puerto Rico,918,United States,"270 Munoz Rivera, San Juan, Puerto Rico, 00918...",9.0,naics-541110puertorico,NaN,NaN,naics,7875177788
19,janelise torres marrero,janelise torres marrero,100.000000,Janelise,Torres Marrero,19039.0,17904.0,NaN,NaN,NaN,...,Puerto Rico,908,United States,"PO Box 9134, San Juan, Puerto Rico, 00908, Uni...",5.0,naics-541110puertorico,NaN,NaN,naics,None
20,jaime munoz salas,jaime munoz salas,100.000000,Jaime,Muñoz Salas,21482.0,23686.0,NaN,NaN,NaN,...,Puerto Rico,928,United States,"PO Box 21490, San Juan, Puerto Rico, 00928, Un...",1.0,naics-541110puertorico,NaN,NaN,naics,None
21,silvestre miranda,silvestre miranda,100.000000,Silvestre,Miranda,4503.0,3167.0,NaN,NaN,NaN,...,Puerto Rico,918,United States,"270 Munoz Rivera, San Juan, Puerto Rico, 00918...",9.0,naics-541110puertorico,NaN,NaN,naics,7875871192
22,jose negron fernandez,jose negron fernandez,100.000000,Jose,Negron Fernandez,12762.0,11456.0,NaN,NaN,NaN,...,Puerto Rico,968,United States,"1510 Fd Roosevelt Ave Ste 9b1, Guaynabo, Puert...",1.0,naics-541110puertorico,NaN,NaN,naics,7876746067
23,alberto perez hernandez,alberto perez hernandez,100.000000,Alberto,Perez Hernandez,7488.0,6081.0,ajperezhdez@gmail.com,NaN,787-753-6455,...,Florida,33134,United States,"133 Aragon Ave, Coral Gables, Florida, 33134, ...",4.0,naics-541110puertorico,NaN,NaN,naics,None
24,rica lopez de alos,rica lopez de alos,100.000000,Rica,Lopez De Alos,12693.0,11407.0,NaN,NaN,NaN,...,Puerto Rico,918,United States,"270 Munoz Rivera, San Juan, Puerto Rico, 00918...",9.0,naics-541110puertorico,NaN,NaN,naics,None
25,angelica curbelo rosa,angelica curbelo rosa,100.000000,Angelica,Curbelo Rosa,21223.0,22200.0,NaN,NaN,NaN,...,Puerto Rico,908,United States,"PO Box 9134, San Juan, Puerto Rico, 00908, Uni...",5.0,naics-541110puertorico,NaN,NaN,naics,3236273303
26,devin santana torres,devin santana torres,100.000000,Devin,Santana Torres,21478.0,23734.0,NaN,NaN,NaN,...,Puerto Rico,968,United States,"100 Carr 165 Ste 509, Guaynabo, Puerto Rico, 0...",2.0,naics-541110puertorico,NaN,NaN,naics,None
27,guimazoa miranda hernandez,guimazoa miranda hernandez,100.000000,Guimazoa,Miranda Hernandez,12793.0,11488.0,NaN,NaN,NaN,...,Puerto Rico,928,United States,"PO Box 21490, San Juan, Puerto Rico, 00928, Un...",1.0,naics-541110puertorico,NaN,NaN,naics,None
28,antonio plaza plaza,antonio plaza plaza,100.000000,Antonio,Plaza Plaza,6336.0,5055.0,NaN,NaN,NaN,...,Puerto Rico,908,United States,"PO Box 9134, San Juan, Puerto Rico, 00908, Uni...",5.0,naics-541110puertorico,NaN,NaN,naics,None
29,anthony santa rivera,anthony santa rivera,100.000000,Anthony,Santa Rivera,21253.0,23115.0,NaN,NaN,NaN,...,Puerto Rico,928,United States,"PO Box 21490, San Juan, Puerto Rico, 00928, Un...",1.0,naics-541110puertorico,NaN,NaN,naics,None
30,miriam ortiz gonzalez,miriam ortiz gonzalez,100.000000,Miriam,Ortiz Gonzalez,14304.0,13128.0,NaN,NaN,NaN,...,Puerto Rico,928,United States,"PO Box 21490, San Juan, Puerto Rico, 00928, Un...",1.0,naics-541110puertorico,NaN,NaN,naics,None
31,carlos rodriguez vidal,carlos rodriguez vidal,100.000000,Carlos,Rodriguez Vidal,9021.0,7791.0,NaN,NaN,NaN,...,Puerto Rico,918,United States,"250 Ave Munoz Rivera Ste 1500, San Juan, Puert...",2.0,naics-541110puertorico,NaN,NaN,naics,7874606061
32,yolanda machado torres,yolanda machado torres,100.000000,Yolanda,Machado Torres,12358.0,11050.0,NaN,NaN,NaN,...,Puerto Rico,908,United States,"PO Box 9134, San Juan, Puerto Rico, 00908, Uni...",5.0,naics-541110puertorico,NaN,NaN,naics,7876026198
33,pedro manzano yates,pedro manzano yates,100.000000,Pedro,Manzano Yates,11173.0,9703.0,pmanzano@scmplex.com,NaN,787-945-0380,...,Puerto Rico,926,United States,Montehiedra Office Centre 9615 Los Romeros Ave...,1.0,naics-541110puertorico,NaN,NaN,naics,None
34,rafael garcia lopez,rafael garcia lopez,100.000000,Rafael,Garcia Lopez,13736.0,12437.0,NaN,NaN,NaN,...,Texas,79401,United States,"1402 Crickets Ave, Lubbock, Texas, 79401, Unit...",11.0,naics-541110puertorico,NaN,NaN,naics,None
35,alba lopez arzola,alba lopez arzola,100.000000,Alba,Lopez Arzola,19000.0,17671.0,lcda.albalopez@gmail.com,NaN,NaN,...,Puerto Rico,918,United States,"304 Ponce De Leon Ave Ste 990, San Juan, Puert...",1.0,naics-541110puertorico,NaN,NaN,naics,None
36,yarimar torres rodriguez,yarimar torres rodriguez,100.000000,Yarimar,Torres Rodriguez,NaN,NaN,NaN,NaN,NaN,...,Puerto Rico,908,United States,"PO Box 9021, San Juan, Puerto Rico, 00908, Uni...",1.0,naics-541110puertorico,NaN,NaN,naics,None
37,guillermo figueroa navarro,guillermo figueroa navarro,100.000000,Guillermo,Figueroa Navarro,20253.0,20626.0,gfn@mcvpr.com,NaN,787-759-9292,...,Puerto Rico,918,United States,"270 Munoz Rivera, San Juan, Puerto Rico, 00918...",9.0,naics-541110puertorico,NaN,NaN,naics,7875671414
38,maricely aponte rivera,maricely aponte rivera,100.000000,Maricely,Aponte Rivera,18186.0,16943.0,NaN,NaN,NaN,...,Puerto Rico,908,United States,"PO Box 9134, San Juan, Puerto Rico, 00908, Uni...",5.0,naics-541110puertorico,NaN,NaN,naics,None
39,yadira colon alicea,yadira colon alicea,100.000000,Yadira,Colon Alicea,16883.0,15839.0,NaN,NaN,NaN,...,Puerto Rico,908,United States,"PO Box 9134, San Juan, Puerto Rico, 00908, Uni...",3.0,naics-541110puertorico,NaN,NaN,naics,None
40,roberto prats palerm,roberto prats palerm,100.000000,Roberto,Prats Palerm,12472.0,11272.0,NaN,NaN,NaN,...,Puerto Rico,918,United States,"270 Munoz Rivera, San Juan, Puerto Rico, 00918...",9.0,naics-541110puertorico,NaN,NaN,naics,7875649929
41,yahaira colon rodriguez,yahaira colon rodriguez,100.000000,Yahaira,Colon Rodriguez,18361.0,17130.0,NaN,NaN,NaN,...,Puerto Rico,928,United States,"PO Box 21490, San Juan, Puerto Rico, 00928, Un...",1.0,naics-541110puertorico,NaN,NaN,naics,None
42,jose soto,jose soto,100.000000,Jose,Soto,5040.0,3729.0,NaN,NaN,NaN,...,Puerto Rico,901,United States,"151 San Franisco St Ste 200, San Juan, Puerto ...",2.0,naics-541110puertorico,NaN,NaN,naics,None
43,coralys cruz perez,coralys cruz perez,100.000000,Coralys,Cruz Perez,21222.0,22609.0,NaN,NaN,NaN,...,Puerto Rico,908,United States,"PO Box 9134, San Juan, Puerto Rico, 00908, Uni...",5.0,naics-541110puertorico,NaN,NaN,naics,None
44,nayla melamed torres,nayla melamed torres,100.000000,Nayla,Melamed Torres,21250.0,23008.0,NaN,NaN,NaN,...,Puerto Rico,928,United States,"PO Box 21490, San Juan, Puerto Rico, 00928, Un...",1.0,naics-541110puertorico,NaN,NaN,naics,None
45,fernando van derdys,fernando van derdys,100.000000,Fernando,Van Derdys,9078.0,7842.0,NaN,NaN,NaN,...,Puerto Rico,917,United States,"255 Ponce De León Avenue Mcs Plz Fl 10, San Ju...",1.0,naics-541110puertorico,NaN,NaN,naics,7875192211
46,samuel cespedes sabater,samuel cespedes sabater,100.000000,Samuel,Cespedes Sabater,10905.0,8797.0,NaN,NaN,NaN,...,Puerto Rico,918,United States,"270 Munoz Rivera, San Juan, Puerto Rico, 00918...",9.0,naics-541110puertorico,NaN,NaN,naics,7876888994
47,gavino rivera ramos,gavino rivera ramos,100.000000,Gavino,Rivera Ramos,16179.0,14772.0,NaN,NaN,NaN,...,NaN,NaN,United States,United States,NaN,naics-541110puertorico,NaN,NaN,naics,None
48,rafael ramirez ball,rafael ramirez ball,100.000000,Rafael,Ramirez Ball,12406.0,11102.0,NaN,NaN,NaN,...,Puerto Rico,919,United States,"195492 Po Box, San Juan, Puerto Rico, 00919, U...",2.0,naics-541110puertorico,NaN,NaN,naics,None
49,aura colon sola,aura colon sola,100.000000,Aura,Colon Sola,19389.0,18843.0,NaN,NaN,787-294-0750,...,Puerto Rico,927,United States,400 Ave. Americo Miranda Edificio Cosvi Origin...,1.0,naics-541110puertorico,NaN,NaN,naics,None
50,jose villamarzo santiago,jose villamarzo santiago,100.000000,Jose,Villamarzo Santiago,14837.0,13635.0,NaN,NaN,NaN,...,Puerto Rico,918,United States,"208 Ponce De Leon Ave Ste 1600, San Juan, Puer...",2.0,naics-541110puertorico,NaN,NaN,naics,None
51,andre palerm colon,andre palerm colon,100.000000,Andre,Palerm Colon,21419.0,21196.0,NaN,NaN,NaN,...,Puerto Rico,918,United States,"270 Munoz Rivera, San Juan, Puerto Rico, 00918...",9.0,naics-541110puertorico,NaN,NaN,naics,7874047746
52,monica agosto pineiro,monica agosto pineiro,100.000000,Monica,Agosto Piñeiro,21511.0,23265.0,NaN,NaN,NaN,...,Puerto Rico,928,United States,"PO Box 21490, San Juan, Puerto Rico, 00928, Un...",1.0,naics-541110puertorico,NaN,NaN,naics,None
53,maria cartagena cancel,maria cartagena cancel,100.000000,Maria,Cartagena Cancel,16904.0,15669.0,NaN,NaN,NaN,...,Puerto Rico,918,United States,"270 Munoz Rivera, San Juan, Puerto Rico, 00918...",9.0,naics-541110puertorico,NaN,NaN,naics,7873073982
54,edgardo rivera rivera,edgardo rivera rivera,100.000000,Edgardo,Rivera Rivera,11112.0,9884.0,edgardo@THERIVERA.group,NaN,787-281-0707,...,Puerto Rico,968,United States,"b-5 Calle Tabonuco B5, Guaynabo, Puerto Rico, ...",1.0,naics-541110puertorico,NaN,NaN,naics,None
55,edgardo rivera rivera,edgardo rivera rivera,100.000000,Edgardo,Rivera Rivera,10264.0,9030.0,NaN,NaN,NaN,...,Puerto Rico,968,United States,"b-5 Calle Tabonuco B5, Guaynabo, Puerto Rico, ...",1.0,naics-541110puertorico,NaN,NaN,naics,None
56,ursula carrion nevarez,ursula carrion nevarez,100.000000,Ursula,Carrion Nevarez,15517.0,14368.0,NaN,NaN,NaN,...,Puerto Rico,968,United States,"400 Rafael Lamar St, Guaynabo, Puerto Rico, 00...",1.0,naics-541110puertorico,NaN,NaN,naics,7873907501
57,jose caceres cardona,jose caceres cardona,100.000000,Jose,Caceres Cardona,20029.0,20077.0,jfcaceres@caceresllc.com,NaN,787-919-0089,...,Puerto Rico,924,United States,"181 Marginal, San Juan, Puerto Rico, 00924, Un...",1.0,naics-541110puertorico,NaN,NaN,naics,None
58,luis perez giusti,luis perez giusti,100.000000,Luis,Perez Giusti,11462.0,10223.0,NaN,NaN,NaN,...,Puerto Rico,918,United States,"208 Ponce De Leon Ave Ste 1600, San Juan, Puer...",2.0,naics-541110puertorico,NaN,NaN,naics,7874587571
59,salvador jimenez santoni,salvador jimenez santoni,100.000000,Salvador,Jimenez Santoni,12353.0,11064.0,NaN,NaN,NaN,...,Puerto Rico,919,United States,"195492 Po Box, San Juan, Puerto Rico, 00919, U...",2.0,naics-541110puertorico,NaN,NaN,naics,7872220842
60,myrna rodriguez rodriguez,myrna rodriguez rodriguez,100.000000,Myrna,Rodriguez Rodriguez,10769.0,9466.0,NaN,NaN,NaN,...,Puerto Rico,908,United States,"PO Box 9134, San Juan, Puerto Rico, 00908, Uni...",3.0,naics-541110puertorico,NaN,NaN,naics,None
61,ricardo agrait defillo,ricardo agrait defillo,100.000000,Ricardo,Agrait Defillo,11855.0,10588.0,NaN,NaN,NaN,...,Puerto Rico,908,United States,"PO Box 9134, San Juan, Puerto Rico, 00908, Uni...",5.0,naics-541110puertorico,NaN,NaN,naics,None
62,veronica gonzalez rodriguez,veronica gonzalez rodriguez,100.000000,Veronica,Gonzalez Rodriguez,18443.0,17143.0,NaN,NaN,NaN,...,Puerto Rico,919,United States,"PO Box 195321, San Juan, Puerto Rico, 00919, U...",NaN,naics-541110puertorico,NaN,NaN,naics,None
63,ricardo diaz soto,ricardo diaz soto,100.000000,Ricardo,Diaz Soto,11731.0,10462.0,NaN,NaN,NaN,...,Puerto Rico,726,United States,"PO Box 2000, Caguas, Puerto Rico, 00726, Unite...",1.0,naics-541110puertorico,NaN,NaN,naics,7875012938
64,karyna cabrera toledo,karyna cabrera toledo,100.000000,Karyna,Cabrera Toledo,17886.0,16624.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,naics-541110puertorico,NaN,NaN,naics,None
65,enrique figueroa llinas,enrique figueroa llinas,100.000000,Enrique,Figueroa Llinas,8938.0,7604.0,NaN,NaN,NaN,...,Puerto Rico,911,United States,"129 De Diego Ave, San Juan, Puerto Rico, 00911...",1.0,naics-541110puertorico,NaN,NaN,naics,7874032566
66,juan alvarez valentin,juan alvarez valentin,100.000000,Juan,Alvarez Valentin,20973.0,21751.0,NaN,NaN,NaN,...,Puerto Rico,918,United States,"270 Munoz Rivera, San Juan, Puerto Rico, 00918...",9.0,naics-541110puertorico,NaN,NaN,naics,None
67,jorge rexach vaquer,jorge rexach vaquer,100.000000,Jorge,Rexach Vaquer,18024.0,16844.0,NaN,NaN,NaN,...,Puerto Rico,918,United States,"270 Munoz Rivera, San Juan, Puerto Rico, 00918...",9.0,naics-541110puertorico,NaN,NaN,naics,7876302687
68,tatiana melendez garcia,tatiana melendez garcia,100.000000,Tatiana,Melendez Garcia,21422.0,23505.0,NaN,NaN,NaN,...,Puerto Rico,917,United States,"255 Ponce De León Avenue Mcs Plz Fl 10, San Ju...",1.0,naics-541110puertorico,NaN,NaN,naics,None
69,edwin otero morales,edwin otero morales,100.000000,Edwin,Otero Morales,21380.0,23037.0,NaN,NaN,NaN,...,Puerto Rico,928,United States,"PO Box 21490, San Juan, Puerto Rico, 00928, Un...",1.0,naics-541110puertorico,NaN,NaN,naics,None
70,lisandra rodriguez moreno,lisandra rodriguez moreno,100.000000,Lisandra,Rodriguez Moreno,13856.0,12668.0,NaN,NaN,NaN,...,Puerto Rico,725,United States,"77 Betances, Caguas, Puerto Rico, 00725, Unite...",2.0,naics-541110puertorico,NaN,NaN,naics,None
71,julio lopez keelan,julio lopez keelan,100.000000,Julio,Lopez Keelan,6248.0,4997.0,NaN,NaN,NaN,...,Puerto Rico,908,United States,"PO Box 9134, San Juan, Puerto Rico, 00908, Uni...",5.0,naics-541110puertorico,NaN,NaN,naics,None
72,claribel gascot nieves,claribel gascot nieves,100.000000,Claribel,Gascot Nieves,10224.0,8966.0,NaN,NaN,NaN,...,Puerto Rico,908,United States,"PO Box 9134, San Juan, Puerto Rico, 00908, Uni...",3.0,naics-541110puertorico,NaN,NaN,naics,None
73,glorimar acevedo cruz,glorimar acevedo cruz,100.000000,Glorimar,Acevedo Cruz,13371.0,12146.0,NaN,NaN,NaN,...,California,94104,United States,"333 Bush St, San Francisco, California, 94104,...",145.0,naics-541110puertorico,NaN,NaN,naics,7875905265
74,enrique umpierre suarez ii,enrique umpierre suarez,93.877551,Enrique,Umpierre Suarez Ii,12045.0,10786.0,NaN,NaN,NaN,...,Puerto Rico,918,United States,Edif. Esquire Ave. Ponce De Leon Esq. Vela Ste...,1.0,naics-541110puertorico,NaN,NaN,naics,None
75,jarrette perez rodriguez,jarrette marie perez rodriguez,88.888889,Jarrette,Perez Rodriguez,20694.0,21758.0,NaN,NaN,NaN,...,Puerto Rico,908,United States,"PO Box 9134, San Juan, Puerto Rico, 00908, Uni...",5.0,naics-541110puertorico,NaN,NaN,naics,None
76,maria gonzalez calderon,maria elena gonzalez calderon,88.461538,Maria,Gonzalez Calderon,13070.0,11794.0,NaN,NaN,NaN,...,Puerto Rico,917,United States,"221 Ponce De Leon Ave, San Juan, Puerto Rico, ...",3.0,naics-541110puertorico,NaN,NaN,naics,None
77,lillianette cortes soto,lillianette cortes,87.804878,Lillianette,Cortes Soto,12813.0,11302.0,NaN,NaN,NaN,...,Puerto Rico,928,United States,"PO Box 21490, San Juan, Puerto Rico, 00928, Un...",1.0,naics-541110puertorico,NaN,NaN,naics,None
78,salvador casellas toro,salvador casellas,87.179487,Salvador,Casellas Toro,9411.0,8194.0,NaN,NaN,NaN,...,Puerto Rico,918,United States,"270 Munoz Rivera, San Juan, Puerto Rico, 00918...",9.0,naics-541110puertorico,NaN,NaN,naics,7876671496
79,francisco marin rodriguez,francisco rodriguez,86.363636,Francisco,Marin Rodriguez,20355.0,19065.0,NaN,NaN,NaN,...,Puerto Rico,918,United States,"250 Muñoz Rivera Ave Ste 800, San Juan, Puerto...",1.0,naics-541110puertorico,NaN,NaN,naics,None
80,manuel lopez gay,manuel lopez,85.714286,Manuel,Lopez Gay,11657.0,10380.0,NaN,NaN,NaN,...,Tennessee,37212,United States,"3210 Orleans Dr, Nashville, Tennessee, 37212, ...",2.0,naics-541110puertorico,NaN,NaN,naics,None

In [ ]:
def pruebas(df1, df2, name1, name2, threshold):
    matches = src.find_fuzzy_matches(df1, df2,name1, name2, threshold)
    evaluacion = src4.test(matches)

    # Suponiendo que tienes:
    y_true = evaluacion["actual"]
    y_pred = evaluacion["predicted"]

    # Confusion matrix
    tn, fp, fn, tp = confusion_matrix(y_true, y_pred).ravel()

    # F1-score
    f1 = f1_score(y_true, y_pred)

    # Mostrar resultados
    print(f"TP: {tp}")
    print(f"TN: {tn}")
    print(f"FP: {fp}")
    print(f"FN: {fn}")
    print(f"F1-score: {f1:.2f}")

    return tn, fp, fn, tp, f1

In [ ]:
pruebas(df_gm, df_ca, "Clean_Name", "FULL NAME", 76)

TP: 99
TN: 399
FP: 9
FN: 85
F1-score: 0.68

(np.int64(399), np.int64(9), np.int64(85), np.int64(99), 0.678082191780822)

In [ ]:
pruebas(df_gm, df_naics, "Clean_Name", "Name_N", 76)
pruebas(df_ca, df_naics, "FULL NAME", "Name_N", 76)

TP: 19
TN: 409
FP: 5
FN: 73
F1-score: 0.33
TP: 185
TN: 799
FP: 24
FN: 155
F1-score: 0.67

(np.int64(799), np.int64(24), np.int64(155), np.int64(185), 0.6739526411657559)

In [ ]:
print(len(df_gm))
print(len(df_ca))
print(len(df_naics))

698
2700
1888